---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Front Page
- type: document
  path: data/en/banner.yml
  label: Hero / Banner
  new_doc_ext: yml
- type: document
  path: data/en/about.yml
  label: About Us
  new_doc_ext: yml
- type: document
  path: data/en/funfacts.yml
  label: At a Glance
- type: document
  path: data/en/works.yml
  label: Our Works
- type: document
  path: data/en/help.yml
  label: Offer Help
- type: document
  path: data/en/more.yml
  label: Learn More
- type: document
  path: data/en/contact.yml
  label: Contact Info
- type: heading
  label: Standalone Pages
- type: document
  path: content/english/standalone/about.md
  label: Who We Are
- type: document
  path: content/english/standalone/works.md
  label: What We Do
- type: document
  path: content/english/standalone/help.md
  label: How to Help
- type: document
  path: content/english/standalone/more.md
  label: Learn More
- type: document
  path: content/english/standalone/projects.md
  label: Projects Page
- type: document
  path: data/en/project-contact.yml
  label: Projects Page Contact
- type: document
  path: content/english/standalone/privacy.md
  label: Privacy Policy
- type: heading
  label: Manage Data
- type: directory
  path: data/en/team
  label: Team Members
  create: documents
  match: "**/*.{yml,yaml,json,toml}"
  new_doc_ext: yml
  templates:
  - member
- type: directory
  path: data/en/board
  label: Board Members
  create: documents
  match: "**/*.{yml,yaml,json,toml}"
  new_doc_ext: yml
  templates:
  - member
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
